### ISSUE TITLE
Flag provided but not defined: -d

### ISSUE THREAD

**Issue by dixonmartinez** [13W/docker-cp#2]
Greeting.
I'm using version 1.10 of docker-engine and tells me that the -d flag is not defined.

That I can do to do funcionameiento your application?
$ docker -d -H=0.0.0.0:4243 -api-enable-cors
docker -d
flag provided but not defined: -d
See 'docker --help'.

**Comment by 13W** [comment]
hello,
`-d` option was replaced with `daemon`, try this:
docker daemon -H fd:// -H tcp://127.0.0.1:4243 --api-cors-header=*

**Comment by dixonmartinez** [comment]
Thank you...
